seeds = [
    "https://docs.cloud.google.com/firestore/docs/samples/firestore-data-set-id-random-collection-async"
]
prefixes = [
    "/firestore/"
]

qpm = 90
discovery = false
sitemaps = ["https://docs.cloud.google.com/sitemap.xml"]
